### ISSUE TITLE
url_helper error when upgrade to Devise 2.0.0

### ISSUE THREAD

**Issue by lanvige** [plataformatec/devise#1625]
I used devise 1.5.3 with Rails 3.2.1 in **mountable engine** and **works well**, but when upgrade the Devise to 2.0.0, the url_helper can't work.
## Error Message:

ActionView::Template::Error (undefined method `user_session_path' for #ActionDispatch::Routing::RoutesProxy:0x4f79760):

```
8:                  <%= simple_form_for(resource, :as => resource_name, :url
```

 => session_path(resource_name)) do |f| %>

  actionpack (3.2.1) lib/action_dispatch/routing/routes_proxy.rb:34:in `method_missing'
  devise (2.0.0) lib/devise/controllers/url_helpers.rb:50:in`session_path'  railsproject/auth/app/views/railsproject/sessions/new.html.erb: 8:in `_d__repos_phoenix_auth_app_views_railsproject_sessions_new_html_erb___982386500_41788656'

I have seen these relative issue, but it just broken after upgrade the version from 1.5.3 to 2.0.0.
https://github.com/plataformatec/devise/issues/1336
https://github.com/plataformatec/devise/issues/1229

Thanks
