### ISSUE TITLE
Error after update rails from 4.1 to 4.2

### ISSUE THREAD

**Issue by mystdeim** [plataformatec/devise#3396]
This line raise error
```ruby
devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
```

Error:
Uncaught exception: undefined method `merge!' for #<ActionDispatch::Routing::Mapper::Scope:0x00000008288c48>
	/home/deim/.rvm/gems/ruby-2.1.3/gems/devise-3.2.4/lib/devise/rails/routes.rb:455:in `ensure in with_devise_exclusive_scope'
	/home/deim/.rvm/gems/ruby-2.1.3/gems/devise-3.2.4/lib/devise/rails/routes.rb:455:in `with_devise_exclusive_scope'
	/home/deim/.rvm/gems/ruby-2.1.3/gems/devise-3.2.4/lib/devise/rails/routes.rb:246:in `block (2 levels) in devise_for'
	/home/deim/.rvm/gems/ruby-2.1.3/gems/devise-3.2.4/lib/devise/rails/routes.rb:349:in `block in devise_scope'
	/home/deim/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:940:in `block in constraints'
	/home/deim/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:816:in `scope'
	/home/deim/.rvm/gems/ruby-2.1.3/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:940:in `constraints'
	/home/deim/.rvm/gems/ruby-2.1.3/gems/devise-3.2.4/lib/devise/rails/routes.rb:348:in `devise_scope'
	/home/deim/.rvm/gems/ruby-2.1.3/gems/devise-3.2.4/lib/devise/rails/routes.rb:245:in `block in devise_for'
	/home/deim/.rvm/gems/ruby-2.1.3/gems/devise-3.2.4/lib/devise/rails/routes.rb:220:in `each'
	/home/deim/.rvm/gems/ruby-2.1.3/gems/devise-3.2.4/lib/devise/rails/routes.rb:220:in `devise_for'
	/data/workspace/rails/onthehook/config/routes.rb:106:in `block in <top (required)>'

**Comment by carlosantoniodasilva** [comment]
Make sure you update to [Devise 3.4.0+, which adds support to Rails 4.2](https://github.com/plataformatec/devise/blob/master/CHANGELOG.md#340---2014-10-03). Thanks.
