### ISSUE TITLE
Incompatibility with bcrypt with rails 3.1 stable branch

### ISSUE THREAD

**Issue by jfelipe** [plataformatec/devise#1284]
I am working with rails 3.1 rc6 and I get the following error 

```
`<module:Devise>': undefined method `weeks' for 2:Fixnum (NoMethodError)
```

I try to update devise but I get this one.

```
Bundler could not find compatible versions for gem "bcrypt-ruby":
  In Gemfile:
    devise (~> 1.4.2) depends on
      bcrypt-ruby (~> 2.1.2)

    rails depends on
      bcrypt-ruby (3.0.0)
```
