### ISSUE TITLE
undefined method `current_sign_in_at'

### ISSUE THREAD

**Issue by pcreux** [plataformatec/devise#51]
Hi there,

since I updated from 0.6.0 to 0.6.2 I get the following error when I create & authenticate a new user: 

```
And I press "Create"            # features/step_definitions/webrat_steps.rb:19
  undefined method `current_sign_in_at' for #<User:0x7f82ee7facb0> (NoMethodError)
  /usr/lib/ruby/gems/1.8/gems/activerecord-2.3.4/lib/active_record/attribute_methods.rb:260:in `method_missing'
  /usr/lib/ruby/gems/1.8/gems/devise-0.6.2/lib/devise/hooks/trackable.rb:5
  /usr/lib/ruby/gems/1.8/gems/warden-0.6.4/lib/warden/proxy.rb:259:in `call'
  /usr/lib/ruby/gems/1.8/gems/warden-0.6.4/lib/warden/proxy.rb:259:in `_perform_authentication'
  /usr/lib/ruby/gems/1.8/gems/warden-0.6.4/lib/warden/proxy.rb:259:in `each'
  /usr/lib/ruby/gems/1.8/gems/warden-0.6.4/lib/warden/proxy.rb:259:in `_perform_authentication'
  /usr/lib/ruby/gems/1.8/gems/warden-0.6.4/lib/warden/proxy.rb:68:in `authenticate'
  /usr/lib/ruby/gems/1.8/gems/devise-0.6.2/lib/devise/controllers/filters.rb:37:in `authenticate'
  /media/disk/Taf/2009_SiggyFeed/apps/trunk/rails_www/app/controllers/users_controller.rb:8:in `create'
```

Here is the code:

  class UsersController < ApplicationController
    def create
      @user = User.new(params[:user])
      if @user.save
        authenticate(:user)
        redirect_to root_path
      else
        render :template => 'home/welcome'
      end
    end
  end
